w

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -36,33 +36,37 @@ jobs:
 
           # Use find to search for the specific file and print its directory paths
             find "$BASE_DIR" -type f -name "$SPECIFIC_FILE" -exec dirname {} \; | sort -u | while read -r DIR_PATH; do
-               
-                ls $DIR_PATH
-                echo "Found directory path: $DIR_PATH"
-                done
-        # TARGET_DIR=$(realpath "$DIR_PATH")
-      
-        # ZIP_NAME="portal.zip"  # Name for the zip file
-        
-        # # Check if the target directory exists
-        # if [[ ! -d "$TARGET_DIR" ]]; then
-        
-        #     echo "Error: Target directory '$TARGET_DIR' does not exist."
-
-        #     continue
-        # fi
-
-        # echo "Zipping contents of '$TARGET_DIR' into '$ZIP_NAME'..."
-        
-        # # Change to the target directory and zip its contents
-        # cd "$TARGET_DIR" || { echo "Error: Failed to change directory to '$TARGET_DIR'."; continue; }
-        
-        # # Check if the zip file already exists
-        # if [[ -e "$ZIP_NAME" ]]; then
-        #     echo "Warning: '$ZIP_NAME' already exists. It will be overwritten."
-        # fi
-
+            TARGET_DIR=$(realpath "$DIR_PATH")
           
+            ZIP_NAME="portal.zip"  # Name for the zip file
+            
+            # Check if the target directory exists
+            if [[ ! -d "$TARGET_DIR" ]]; then
+            
+                echo "Error: Target directory '$TARGET_DIR' does not exist."
+
+                continue
+            fi
+
+            echo "Zipping contents of '$TARGET_DIR' into '$ZIP_NAME'..."
+              # Save the current directory
+              original_dir=$(pwd)
+            
+            # Change to the target directory and zip its contents
+            cd "$TARGET_DIR" || { echo "Error: Failed to change directory to '$TARGET_DIR'."; continue; }
+            
+            # Check if the zip file already exists
+            if [[ -e "$ZIP_NAME" ]]; then
+                echo "Warning: '$ZIP_NAME' already exists. It will be overwritten."
+            fi
+
+             # Change back to the original directory
+              cd "$original_dir" || { echo "Error: Failed to return to original directory '$original_dir'."; exit 1; }
+            done
+
+          # ls $DIR_PATH
+          #       echo "Found directory path: $DIR_PATH"
+          #       done
 
 
         # # Use find to search for the specific file and print its directory paths
