w

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -35,40 +35,40 @@ jobs:
           echo "Searching for '$SPECIFIC_FILE' in directories under '$BASE_DIR':"
 
           # Use find to search for the specific file and print its directory paths
-            find "$BASE_DIR" -type f -name "$SPECIFIC_FILE" -exec dirname {} \; | sort -u | while read -r DIR_PATH; do
-            TARGET_DIR=$(realpath "$DIR_PATH")
-            echo "DIR path '$DIR_PATH'"
-            ZIP_NAME="portal.zip"  # Name for the zip file
-            
-            # Check if the target directory exists
-            if [[ ! -d "$TARGET_DIR" ]]; then
-            
-                echo "Error: Target directory '$TARGET_DIR' does not exist."
+           find "$BASE_DIR" \( -type d -name "content" -o -type d -name "static" -o -type f -name "$SPECIFIC_FILE" \) -exec dirname {} \; | sort -u | while read -r DIR_PATH; do
+           TARGET_DIR=$(realpath "$DIR_PATH")
+          echo "DIR path '$DIR_PATH'"
+      # ZIP_NAME="portal.zip"  # Name for the zip file
+      
+      # # Check if the target directory exists
+      # if [[ ! -d "$TARGET_DIR" ]]; then
+      
+      #     echo "Error: Target directory '$TARGET_DIR' does not exist."
 
-                continue
-            fi
+      #     continue
+      # fi
 
 
-            echo "Zipping contents of '$TARGET_DIR' into '$ZIP_NAME'..."
-              # Save the current directory
-              original_dir=$(pwd)
-            
-            # Change to the target directory and zip its contents
-            cd "$TARGET_DIR" || { echo "Error: Failed to change directory to '$TARGET_DIR'."; continue; }
-            
-            # Check if the zip file already exists
-            if [[ -e "$ZIP_NAME" ]]; then
-                echo "Warning: '$ZIP_NAME' already exists. It will be overwritten."
-            fi
+      # echo "Zipping contents of '$TARGET_DIR' into '$ZIP_NAME'..."
+      #   # Save the current directory
+      #   original_dir=$(pwd)
+      
+      # # Change to the target directory and zip its contents
+      # cd "$TARGET_DIR" || { echo "Error: Failed to change directory to '$TARGET_DIR'."; continue; }
+      
+      # # Check if the zip file already exists
+      # if [[ -e "$ZIP_NAME" ]]; then
+      #     echo "Warning: '$ZIP_NAME' already exists. It will be overwritten."
+      # fi
 
-            zip -r "$ZIP_NAME" ./*  # Zip contents and place it in the base directory
-            #   echo "Created zip file: $ZIP_NAME"
-            # Unzip and list contents of the zip file
-            echo "Unzipping '$ZIP_NAME' to list its contents..."
-            unzip -l "$ZIP_NAME"  # List contents of the zip file
-             # Change back to the original directory
-              cd "$original_dir" || { echo "Error: Failed to return to original directory '$original_dir'."; exit 1; }
-            done
+      # zip -r "$ZIP_NAME" ./*  # Zip contents and place it in the base directory
+      # #   echo "Created zip file: $ZIP_NAME"
+      # # Unzip and list contents of the zip file
+      # echo "Unzipping '$ZIP_NAME' to list its contents..."
+      # unzip -l "$ZIP_NAME"  # List contents of the zip file
+      #  # Change back to the original directory
+      #   cd "$original_dir" || { echo "Error: Failed to return to original directory '$original_dir'."; exit 1; }
+      # done
 
         # ls $DIR_PATH
         #       echo "Found directory path: $DIR_PATH"
